//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NikolaMilosevicKonzoleProdajem
{
    public partial class admin
    {
        protected global::System.Web.UI.WebControls.Button logoutButton;
        protected global::System.Web.UI.WebControls.GridView markaGrid;
        protected global::System.Web.UI.WebControls.TextBox markeBox;
        protected global::System.Web.UI.WebControls.Button markeButton;
        protected global::System.Web.UI.WebControls.DropDownList markaComboBox;
        protected global::System.Web.UI.WebControls.Button markaDeleteButton;
        protected global::System.Web.UI.WebControls.GridView modelGrid;
        protected global::System.Web.UI.WebControls.DropDownList modelMarkaBox;
        protected global::System.Web.UI.WebControls.TextBox modelBox;
        protected global::System.Web.UI.WebControls.Button modelButton;
        protected global::System.Web.UI.WebControls.DropDownList modelMarkaComboBox;
        protected global::System.Web.UI.WebControls.DropDownList modelComboBox;
        protected global::System.Web.UI.WebControls.Button modelDeleteButton;
        protected global::System.Web.UI.WebControls.GridView lokacijaGrid;
        protected global::System.Web.UI.WebControls.TextBox lokacijaBox;
        protected global::System.Web.UI.WebControls.Button lokacijaButton;
        protected global::System.Web.UI.WebControls.DropDownList lokacijaComboBox;
        protected global::System.Web.UI.WebControls.Button lokacijaDeleteButton;
        protected global::System.Web.UI.WebControls.GridView stanjeGrid;
        protected global::System.Web.UI.WebControls.TextBox stanjeBox;
        protected global::System.Web.UI.WebControls.Button stanjeButton;
        protected global::System.Web.UI.WebControls.DropDownList stanjeComboBox;
        protected global::System.Web.UI.WebControls.Button stanjeDeleteButton;
        protected global::System.Web.UI.WebControls.GridView garancijaGrid;
        protected global::System.Web.UI.WebControls.TextBox garancijaBox;
        protected global::System.Web.UI.WebControls.Button garancijaButton;
        protected global::System.Web.UI.WebControls.DropDownList garancijaComboBox;
        protected global::System.Web.UI.WebControls.Button garancijaDeleteButton;
        protected global::System.Web.UI.WebControls.GridView valutaGrid;
        protected global::System.Web.UI.WebControls.TextBox valutaImeBox;
        protected global::System.Web.UI.WebControls.TextBox valutaSimbolBox;
        protected global::System.Web.UI.WebControls.TextBox valutaKursBox;
        protected global::System.Web.UI.WebControls.Button valutaButton;
        protected global::System.Web.UI.WebControls.DropDownList valutaComboBox;
        protected global::System.Web.UI.WebControls.Button valutaDeleteButton;
        protected global::System.Web.UI.WebControls.Label poruka;
    }
}
