//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NikolaMilosevicKonzoleProdajem
{
    public partial class new_oglas
    {
        protected global::System.Web.UI.WebControls.TextBox nameBox;
        protected global::System.Web.UI.WebControls.TextBox descriptionBox;
        protected global::System.Web.UI.WebControls.TextBox priceBox;
        protected global::System.Web.UI.WebControls.DropDownList valutaBox;
        protected global::System.Web.UI.WebControls.DropDownList markaBox;
        protected global::System.Web.UI.WebControls.DropDownList modelBox;
        protected global::System.Web.UI.WebControls.TextBox memorijaBox;
        protected global::System.Web.UI.WebControls.DropDownList stanjeBox;
        protected global::System.Web.UI.WebControls.DropDownList garancijaBox;
        protected global::System.Web.UI.WebControls.FileUpload fileUpload;
        protected global::System.Web.UI.WebControls.Button finishButton;
        protected global::System.Web.UI.WebControls.Label poruka;
    }
}
